# Generated by Django 4.1.3 on 2022-11-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journal_entry_delete_diary_entry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Journal_entry',
            new_name='JournalEntry',
        ),
    ]
