# Generated by Django 4.1.3 on 2022-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_journalentry_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
