# Generated by Django 4.1.3 on 2023-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_journalentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default='2023-01-14'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
