# Generated by Django 4.1.3 on 2023-06-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_journalentry_date_alter_journalentry_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default='2023-06-25'),
        ),
    ]
